### ISSUE TITLE
Provide QPlatformTheme::{MouseCursorTheme,MouseCursorSize} on qt6

### ISSUE THREAD

**Issue by q234rty** [lxqt/lxqt-qtplugin#78]
Qt 6.5 [introduced](https://invent.kde.org/qt/qt/qtbase/-/commit/a823366f7745c235a752dc01c42276b3fa410937) QPlatformTheme::{MouseCursorTheme,MouseCursorSize} which are being used instead on `XCURSOR_THEME` and `XCURSOR_SIZE` on [wayland](https://invent.kde.org/qt/qt/qtwayland/-/commit/fdbc9e113b7c4361f148508c8332487d9385105d). This breaks cursor size for me when using the lxqt qt6 plugin on the wip_qt6 branch, as otherwise qt falls back on `QGenericUnixTheme` which reads `XCURSOR_THEME` and `XCURSOR_SIZE`.

**Comment by tsujan** [comment]
Thanks for the info!

Will check it after LXQt 1.3.0 is released (soon) and, perhaps, after [`libdbusmenu-lxqt`](https://github.com/lxqt/libdbusmenu-lxqt) is ready (shouldn't take long either).

**Comment by q234rty** [comment]
If the plan is to have a qt6-based 1.3.0 then imo at least the previous behavior i.e. reading `XCURSOR_SIZE` and `XCURSOR_THEME` should be restored before 1.3.0. Otherwise it's fine to leave this after 1.3.0

**Comment by tsujan** [comment]
> If the plan is to have a qt6-based 1.3.0

1.3.0 will be released in a few days (according to the schedule), based on Qt 5.15. We're waiting for a stable release of KF6 in order to port the whole LXQt to Qt6.

**Comment by stefonarch** [comment]
Noticed just now that increasing  cursor size from 28 to 32 cursor will change back to 28 in qt6 apps.

**Comment by tsujan** [comment]
@q234rty 
Does https://github.com/lxqt/lxqt-qtplugin/pull/85 fix the problem for you?
