### ISSUE TITLE
Making tool-bar icon size configurable?

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-qtplugin#90]
Some users may need to have a small tool-bar icon size, and the parameter `ToolBarIconSize` exists for that, but we don't set it. Should we set it?

Please note that apps as well as Qt styles are free to ignore it.

**Comment by palinek** [comment]
For me yes. You are the advocate of not cluttering the configuration possibilities :-D. So if you're ok with it, I second that.

**Comment by tsujan** [comment]
A user wanted it in pcmanfm-qt and, of course, I was against it ;)  But his use case was related to his device; hence proposing a global option here.

So, we could add a few lines of codes to lxqt-qtplugin and lxqt-config, telling in a tooltip of the latter that the setting could be overridden by apps or Qt styles.

**Comment by tsujan** [comment]
Oh, I forgot this — and might do again if I don't make 2 PRs ;)

@stefonarch 
Two members agree. Do you?

**Comment by stefonarch** [comment]
Who am I to say no when YOU want to add an option :)

**Comment by tsujan** [comment]
> when YOU want to add an option

I'm innocent; only against making a jungle of options.

The PR for lxqt-qtplugin will be elementary, but the one for lxqt-config will need some work.
