### ISSUE TITLE
liblxqt is falsely advertised as a dependency in the README.md file

### ISSUE THREAD

**Issue by severusseptimius** [lxqt/lxqt-qtplugin#94]
liblxqt has not been needed since #15. However the readme file says

> Runtime dependencies are [libdbusmenu-lxqt](https://github.com/lxqt/libdbusmenu-lxqt) and [liblxqt](https://github.com/lxqt/liblxqt).

**Comment by stefonarch** [comment]
`CMakeList.txt` is looking for 
```
# Minimum Versions
set(LXQTBT_MINIMUM_VERSION "2.0.0")
...
set(QTXDG_MINIMUM_VERSION "4.0.0")
```

and the Qt5 stuff is outdated completely. Need an ovehaul, yes.
